version: '3.9'
services:
  consumer:
    build:
      context: ./
      dockerfile: consumer/dockerfile
    depends_on:
      - broker
    volumes:
      - ./data:/consumer/data

  producer:
    build: producer
    depends_on:
      - broker
    volumes:
      - ./PS_20174392719_1491204439457_log.csv:/producer/PS_20174392719_1491204439457_log.csv:ro
    command: ["broker", "9092", "wiki", "5000000000000000"]

  broker:
    build: broker
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=keeper:2181    
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - keeper

  keeper:
    image: bitnami/zookeeper:3.7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  node:
    build: node
    environment:
      - HEAP_NEWSIZE=1024M
      - MAX_HEAP_SIZE=2048M
    ports:
      - 9042:9042

  api:
    build: 
      context: ./
      dockerfile: api/dockerfile
    depends_on:  
      - node
    ports:
      - 8080:8080
    environment:
      - C_NODE=node
      - C_PORT=9042
      - C_KEYSPACE=l_04