FROM python:3.10
WORKDIR /usr/src/
COPY api/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY api/start.sh ./
COPY api/api.py ./
COPY common/ ./common/
RUN chmod +x start.sh
ENTRYPOINT [ "./start.sh" ]